"""
Price Validator - Router
========================
FastAPI endpoints for the Price Data validation service.
"""
from fastapi import APIRouter, UploadFile, File, HTTPException, BackgroundTasks
from fastapi.responses import JSONResponse
from typing import Optional
import tempfile
import os
import logging
import traceback

from .graph import run_troubleshooting
from .schemas import ValidateFileOutput, ValidateFileStatusOutput

from app.shared.async_runs import (
    create_run,
    get_run,
    set_run_completed,
    set_run_failed,
    update_run,
    update_run_progress,
)

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post("/validate-file", response_model=ValidateFileOutput)
async def validate_price_data_file(
    file: UploadFile = File(..., description="Price Data dataset in CSV or Excel format"),
    template: Optional[UploadFile] = File(None, description="Optional template (.csv or .xlsx)")
):
    """
    Validates a Price Data dataset (CSV or Excel).
    
    Performs 5 layers of validation:
    - Layer 0: File Validation (encoding, format)
    - Layer 1: Structural Parsing (delimiter, broken rows)
    - Layer 2: Schema Validation (required columns, language)
    - Layer 3: Product Classification (matching products against the official WFP list)
    - Layer 4: Report Generation (diagnostic report generated by the LLM)
    
    Returns:
        ValidateFileOutput with results for each layer and the final report
    """
    
    # Input validation
    if not file.filename:
        raise HTTPException(status_code=400, detail="Missing filename")
    
    valid_extensions = ['.csv', '.xlsx', '.xls']
    file_ext = os.path.splitext(file.filename)[1].lower()
    
    if file_ext not in valid_extensions:
        raise HTTPException(
            status_code=400, 
            detail=f"Unsupported file format. Use: {', '.join(valid_extensions)}"
        )
    
    # Save temporary file
    tmp_path = None
    template_path = None
    
    try:
        # Save main file
        with tempfile.NamedTemporaryFile(delete=False, suffix=file_ext) as tmp:
            content = await file.read()
            tmp.write(content)
            tmp_path = tmp.name
        
        # Save template if provided
        if template:
            template_ext = os.path.splitext(template.filename)[1].lower()
            with tempfile.NamedTemporaryFile(delete=False, suffix=template_ext) as tmp_t:
                template_content = await template.read()
                tmp_t.write(template_content)
                template_path = tmp_t.name
        
        # Perform validation
        logger.info(f"Starting validation for: {file.filename}")
        
        result = run_troubleshooting(
            file_path=tmp_path,
            template_path=template_path
        )
        
        # Calculate success
        layer_results = result.get("layer_results", [])
        success = all(lr.get("passed", False) for lr in layer_results)
        
        # Build output
        output = ValidateFileOutput(
            file_name=file.filename,
            file_type=result.get("file_type"),
            country=result.get("country"),
            num_products=result.get("num_products"),
            num_markets=result.get("num_markets"),
            detected_language=result.get("detected_language"),
            llm_calls=result.get("llm_calls", 0),
            layer_results=layer_results,
            product_classifications=result.get("product_classifications", []),
            final_report=result.get("final_report", ""),
            success=success
        )
        
        logger.info(f"Validation completed for {file.filename}: success={success}")
        
        return output
        
    except Exception as e:
        logger.error(f"Validation error for {file.filename}: {e}")
        raise HTTPException(status_code=500, detail=str(e))
    
    finally:
        # Cleanup temporary files
        if tmp_path and os.path.exists(tmp_path):
            os.unlink(tmp_path)
        if template_path and os.path.exists(template_path):
            os.unlink(template_path)


@router.post("/validate-file-async")
async def validate_price_data_file_async(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(..., description="Price Data dataset in CSV or Excel format"),
    template: Optional[UploadFile] = File(None, description="Optional template (.csv or .xlsx)")
):
    if not file.filename:
        raise HTTPException(status_code=400, detail="Missing filename")

    valid_extensions = ['.csv', '.xlsx', '.xls']
    file_ext = os.path.splitext(file.filename)[1].lower()

    if file_ext not in valid_extensions:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file format. Use: {', '.join(valid_extensions)}"
        )

    import uuid

    run_id = f"price_val_{uuid.uuid4().hex[:8]}"
    create_run(run_id)

    original_filename = file.filename

    tmp_path = None
    template_path = None

    with tempfile.NamedTemporaryFile(delete=False, suffix=file_ext) as tmp:
        content = await file.read()
        tmp.write(content)
        tmp_path = tmp.name

    if template:
        template_ext = os.path.splitext(template.filename)[1].lower()
        with tempfile.NamedTemporaryFile(delete=False, suffix=template_ext) as tmp_t:
            template_content = await template.read()
            tmp_t.write(template_content)
            template_path = tmp_t.name

    progress_map = {
        "layer0": 10,
        "layer1": 30,
        "layer2": 55,
        "layer3": 80,
        "report": 95,
    }

    def run_in_background():
        try:
            update_run(run_id, status="running", error=None, traceback=None)

            def on_step(node_name: str, _state: dict):
                progress = progress_map.get(node_name)
                if progress is not None:
                    update_run_progress(run_id, current_node=node_name, progress_pct=progress)
                else:
                    update_run(run_id, current_node=node_name)

            result = run_troubleshooting(
                file_path=tmp_path,
                template_path=template_path,
                on_step=on_step,
            )

            layer_results = result.get("layer_results", [])
            success = all(lr.get("passed", False) for lr in layer_results)

            output = {
                "file_name": original_filename,
                "file_type": result.get("file_type"),
                "country": result.get("country"),
                "num_products": result.get("num_products"),
                "num_markets": result.get("num_markets"),
                "detected_language": result.get("detected_language"),
                "llm_calls": result.get("llm_calls", 0),
                "layer_results": layer_results,
                "product_classifications": result.get("product_classifications", []),
                "final_report": result.get("final_report", ""),
                "success": success,
            }

            set_run_completed(run_id, result=output)

        except Exception as e:
            tb_str = traceback.format_exc()
            current_node = get_run(run_id).current_node if get_run(run_id) is not None else None
            set_run_failed(run_id, error=str(e), traceback=tb_str, current_node=current_node)

        finally:
            if tmp_path and os.path.exists(tmp_path):
                os.unlink(tmp_path)
            if template_path and os.path.exists(template_path):
                os.unlink(template_path)

    background_tasks.add_task(run_in_background)
    return {"run_id": run_id, "status": "pending"}


@router.get("/status/{run_id}", response_model=ValidateFileStatusOutput)
async def get_validate_status(run_id: str):
    run = get_run(run_id)
    if run is None:
        raise HTTPException(status_code=404, detail=f"Run ID not found: {run_id}")

    return ValidateFileStatusOutput(
        run_id=run_id,
        status=run.status,
        current_node=run.current_node,
        progress_pct=run.progress_pct,
        warnings=run.warnings,
        error=run.error,
        traceback=run.traceback,
    )


@router.get("/result/{run_id}", response_model=ValidateFileOutput)
async def get_validate_result(run_id: str):
    run = get_run(run_id)
    if run is None:
        raise HTTPException(status_code=404, detail=f"Run ID not found: {run_id}")

    if run.status != "completed":
        raise HTTPException(
            status_code=400,
            detail=f"Validation not completed. Current status: {run.status}"
        )

    result = run.result or {}
    return ValidateFileOutput(**result)


@router.get("/info")
def get_service_info():
    """
    Returns metadata for the frontend.
    
    The frontend can use this information to dynamically build the input form.
    """
    return {
        "id": "price-validator",
        "name": "Price Data Validator",
        "description": "Validates Price Data datasets (CSV or Excel) with 5 layers of validation. "
                       "Detects structural errors, non-conformant schema, "
                       "classifies products against the official WFP list "
                       "and generates a detailed diagnostic report.",
        "version": "1.0.0",
        "inputs": [
            {
                "name": "file",
                "type": "file",
                "required": True,
                "accept": ".csv,.xlsx,.xls",
                "label": "Price Data dataset",
                "description": "CSV or Excel file containing the price data to validate"
            },
            {
                "name": "template",
                "type": "file",
                "required": False,
                "accept": ".csv,.xlsx,.xls",
                "label": "Template (optional)",
                "description": "Custom template for validating columns"
            }
        ],
        "outputs": {
            "file_name": "Validated file name",
            "file_type": "File type (CSV/EXCEL)",
            "country": "Country detected from dataset",
            "num_products": "Number of unique products",
            "num_markets": "Number of unique markets",
            "detected_language": "Detected language (en, fr, es, ar)",
            "llm_calls": "Number of LLM calls performed",
            "layer_results": "Detailed results for each layer",
            "product_classifications": "Product classifications with confidence",
            "final_report": "Diagnostic report generated by the LLM",
            "success": "True if all layers passed"
        },
        "layers": [
            {"id": 0, "name": "File Validation", "description": "Checks encoding, format, and extension"},
            {"id": 1, "name": "Structural Parsing", "description": "Detects delimiter and broken rows"},
            {"id": 2, "name": "Schema Validation", "description": "Checks required columns and language"},
            {"id": 3, "name": "Product Classification", "description": "Classifies products against the official WFP list"},
            {"id": 4, "name": "Report Generation", "description": "Generates a diagnostic report with the LLM"}
        ],
        "supported_formats": ["CSV", "Excel (.xlsx, .xls)"],
        "product_list_size": "~200 WFP standard products"
    }


@router.get("/health")
def health_check():
    """Health check endpoint."""
    return {"status": "healthy", "service": "price-validator"}


@router.get("/products")
def get_wfp_products():
    """
    Returns the list of recognized WFP products.
    Useful for debugging and reference.
    """
    from .graph import WFP_PRODUCTS
    
    return {
        "total": len(WFP_PRODUCTS),
        "products": [
            {"name": name, "id": pid}
            for name, pid in sorted(WFP_PRODUCTS.items())
        ]
    }