steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_DEPLOY_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_DEPLOY_TAG}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-west1
  _ARTIFACT_REPOSITORY: vam-unified-phase4
  _IMAGE_NAME: unified-app
  _DEPLOY_TAG: phase4
